version: '3.1'

services:

  ff_nginx:
    container_name: ff_nginx
    build: ./.env
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_NPM_PORT}:${WORKSPACE_NPM_PORT}"
    expose:
      - 80
      - 443
      - ${WORKSPACE_NPM_PORT}
    env_file:
      - ./env/nginx/.env
    tty: true
    environment:
      - VIRTUAL_ROOT=${NGINX_VIRTUAL_ROOT}
      - VIRTUAL_HOST=${NGINX_VIRTUAL_HOST}
      - VIRTUAL_PORT=${NGINX_VIRTUAL_PORT}
      - VIRTUAL_PROTO=${NGINX_VIRTUAL_PROTO}
      - LETSENCRYPT_EMAIL=${NGINX_LETSENCRYPT_EMAIL}
      - LETSENCRYPT_HOST=${NGINX_LETSENCRYPT_HOST}
      - LETSENCRYPT_TEST=${NGINX_LETSENCRYPT_TEST}
      - ENABLE_IPV6=${NGINX_ENABLE_IPV6}
    volumes:
      - ./dist:/home/www/faceandfiguresalon
      - ./data/nginx/logs:/var/log/nginx
      - ./env/nginx/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nginx/webserver/conf.d:/etc/nginx/conf.d
      - ./env/nginx/webserver/defaults:/etc/nginx/defaults
      - ./env/nginx/webserver/global:/etc/nginx/global
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy
