version: '3.1'

services:

  ff_nginx:
    container_name: ff_nginx
    build: ./.env
    ports:
      - 8080:8080
    expose:
      - 80
      - 443
    env_file:
      - ./env/nginx/.env
    tty: true
    volumes:
      - ./src:/home/www/naturalremedy/src
      - ./storage:/home/www/storage/naturalremedy
      - ./data/nginx/logs:/var/log/nginx
      - ./env/nginx/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nginx/webserver/conf.d:/etc/nginx/conf.d
      - ./env/nginx/webserver/defaults:/etc/nginx/defaults
      - ./env/nginx/webserver/global:/etc/nginx/global
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy