// Code generated by Slice Machine. DO NOT EDIT.

import ContactPoint from './ContactPoint';
import SellingPoints from './SellingPoints';
import Treatments from './Treatments';

export {
	ContactPoint,
	SellingPoints,
	Treatments,
};

export const components = {
	contact_point: ContactPoint,
	selling_points: SellingPoints,
	treatments: Treatments,
};
